Q-1 Write a Python Program to Add Two Matrices?
x= [[12, 7, 3],[4,5,6],[7, 8 ,9]]
y= [[5, 8, 1],[6, 7, 3],[4, 5, 9]]

In [1]:
x= [[12, 7, 3],[4,5,6],[7, 8 ,9]]
y= [[5, 8, 1],[6, 7, 3],[4, 5, 9]]
result= [[0, 0, 0],[0, 0, 0],[0, 0, 0]]
for i in range (len(x)):
    for j in range(len(x[0])):
        result[i][j]= x[i][j]+ y[i][j]
print(result)

[[17, 15, 4], [10, 12, 9], [11, 13, 18]]


Q-2 Write a Python Program to Multiply Two Matrices?

In [2]:
x= [[12, 7, 3],[4,5,6],[7, 8 ,9]]
y= [[5, 8, 1],[6, 7, 3],[4, 5, 9]]
result= [[0, 0, 0],[0, 0, 0],[0, 0, 0]]
for i in range (len(x)):
    for j in range(len(x[0])):
        result[i][j]= x[i][j]* y[i][j]
print(result)

[[60, 56, 3], [24, 35, 18], [28, 40, 81]]


Q-3 Write a Python Program to Transpose a Matrix?

In [3]:
import numpy as np
matrix=[[1,2,3],[4 ,5 ,6],[7,8 ,9]]
print("\n")
print(np.transpose(matrix))



[[1 4 7]
 [2 5 8]
 [3 6 9]]


Q-4 Write a Python Program to Sort Words in Alphabetic Order?

In [ ]:
my_str= input( "Enter a string ")

In [ ]:
words= my_str.split()
words.sort()
#print("The sorted words are:")
for i in words:
    print(i)

Q-5.Write a Python Program to Remove Punctuation From a String?
[Hint : Used regular expression package]

In [6]:
import re
a = "abijit. barik. Removing. Punctuation??"

In [7]:
a = re.sub(r'[^\w\s]'," ",a)

In [8]:
print(a)

abijit  barik  Removing  Punctuation  
